name: actionlint

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    uses: Obsidian-Solutions/.github/.github/workflows/actionlint.yml@f7e08abb84a2fb948b6ca3d5e095b34c027d12a7
